apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nvisionx-development
  namespace: argocd
spec:
  description: Workloads deployed to eks-development
  sourceRepos:
    - 'https://github.com/Nvision-x/*'
    - 'https://argoproj.github.io/argo-helm'
    - 'ghcr.io/nvision-x'
    - 'ghcr.io/nvision-x/*'
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
