apiVersion: v1
kind: Secret
metadata:
  name: eks-development
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: development
type: Opaque
stringData:
  name: eks-development
  server: https://32695B4EB6F77EAAEE06750AE02D58D1.gr7.us-east-1.eks.amazonaws.com
  config: |
    {
      "awsAuthConfig": {
        "clusterName": "eks-development",
        "roleARN": "arn:aws:iam::769537049595:role/eks-development-argocd-target"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQW44YVkyOUJHazB3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFd016QXhNekEwTVRCYUZ3MHpOVEV3TWpneE16QTVNVEJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN4T3U5Q2hnSEllbWFEcHhkaTMzcllUVlE3RS9PRStTM25CSi9hRXAxdFBtZ2FjWkRHUHdBWU9reUEKUmFPRWJ4T0RTa0pmdzhTc2RpQzZDWkxWQlBMVGZ4RU5BN2xQSHA0QzF1VWlMclMxNGtlNmhIT2h6ZmllUllrWApyL2JmQlhmck5zSTFrR3RuRUJ1SURWeFlPSmNuQlY0TVBRRm9zODV3dkx2MXg3L2hDdjMyR0VwdVpRbWRpVzdoCjB3TmVQMXNoZEJET0NRalpJWVlSa0xGVzA1bTB4cHNtL3VtMmZiZFduK3RCRWUzU3V5cWlITUxMWEkyRVdGQVoKTzk4Smt1bGxUVkplMkhUUityNi82YlN3eU5pV1FyTXMxdXJzTWJwQy9Vc0txNHdNL3BWemgwUmM2M2dybWIvNwo4QWdBMTNER2cvYUJ6cDNkVTdQT3JVSGxCZGhiQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTdkcrYmJJdG8rend4Y2VHdk9HdGtwUElIcExqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQi9kbHd5L2dkNgp5WkE1OVc5RXo4azJ4bWpnSm5UT2NWa3hvQ2lPbFYrTnc0MndIZlVZaGlYRE9NeHJHd2VYRmVPV0kzam9QdEQrCkQrbjdWc2QreURYelhTazNBWG84NXVZQXBIaG56UVdLNXVrTE5GSjdOZmlSTnBUMXVkOW5hOE5zTWJSMitIMzEKSTNiYkpYWUFCOU1wWnhmR3VGYzFNUmc0d3JSOHN0a2RwSDFKK3VPbEMwVzZyaWVVdFFSMHBtR1JxRlpxUjFCNQpieThETVQxSmsyaXJLcXJYYndlU0VNcHE3ekFVMWxrTkV4TmlUOWcwTENvNnMzZlRqK2VNWlpDNW1laXdzcWltCm5SSktTQkZ0SXhBUWRVRi9sWXJSc2VvUjE4ZjNicTE4aEVaT081ZVJ3WFk1Ri9wZmxYcXQzaS9WQXJKRHMydUsKTzFDbzVwLzBISFpHCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      }
    }
