apiVersion: v1
kind: Secret
metadata:
  name: eks-demo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: demo
type: Opaque
stringData:
  name: eks-demo
  server: https://32B0BF53BDBB47C2D9E4ECD3428D07FE.gr7.us-east-1.eks.amazonaws.com
  config: |
    {
      "awsAuthConfig": {
        "clusterName": "eks-demo",
        "roleARN": "arn:aws:iam::864456253006:role/eks-demo-argocd-target"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWGd6M0luNEJYSTB3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBNU1UWXhPRFV3TURCYUZ3MHpOVEE1TVRReE9EVTFNREJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMzWnkvbjRyUGV2N05BUStSNlNaVitrcFMxRGpBSG1RYmxnYmdrM2Z6WnpxS1g2cnUzdjNmckJ5bysKWFN2VnBVSUgxL0huZ3owV0NsdVdDa080TWdmeUt3MjE4bkh4VEp3QmIwNDlPWFZDMW8vN1A1RUk2UmR1a0p3YQpqcGltUjFtOS9HdldzNThIY0I4NC9YQWk2UUZhcGdTazFpdGhaSGxGVGN6emVrRU5yd0NVREl2UDM4Tko5bU1lCnZZMlJGNmt1eVZkZTFWM0U5eERUSHVwbE83MXZ3NEFhQ0lqUFI4MG0wdTlzaVVhYlpCQmNpejNHS3RUK2NoUzkKNEhjQUk5cDNXU0Jmc1hCa2J1Q0Vac3RGcFQ2YVdnUDFnYThLUUJ4eiswZTRubklLRUJIQUR5V3JKN0VMT2ZKUQo3QkFTODNDdWc3RytIU0RxNkpTMEV4RmhFdHpaQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTSThxUlpySVE3QnB1bGVnNXRyVjA1QjFPK1lEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ3hLYkN5c0pETwo2TjZMQ09ERVBtUC95dHJFRXg5Mk04NDBTaVRadTVGWUxyV2FvR3YzSlBJMDFNQVRaUHEzVzF0ZERWVENVNWlyCmIxSmhkdC9GS3ArQ1VCeWVUQXhOV3RpcitHdG9FSkVGQWxiWlVtcWlwL3FtcEN0eUtmelRXZjhBOWdJMmJjRW4Kd1k4OW52b1J0ZmRwVGs1L3A0aE1Sc05hZ1E0M0hOM0xWOFJmbzczenBYNGF4WFlvbE5oQlZEQlVPcWNKZXlvSQp2dUdpSHBpWnB0YTZna1pjTHZYUzcxVEJCZ2JlTmdTRWRyc3FNbUlzVlVvaGhCTHdWRkd2WThVVjRYNnRNTGRzCjFNYkxobm1MT2JHVTYvOHhNMW5NaEZpL3VKZjAvUmVNT1RWVTFDNUxJdEkwOXZwV2ZTMGVOQWNUK0JaK29HNGQKckdqSjZobGJ0SExlCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      }
    }
