apiVersion: v1
kind: Secret
metadata:
  name: eks-demo2
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: demo2
type: Opaque
stringData:
  name: eks-demo2
  server: https://780B45C82AC2BD4FD30821D8BB8404AE.gr7.us-east-2.eks.amazonaws.com
  config: |
    {
      "awsAuthConfig": {
        "clusterName": "eks-demo2",
        "roleARN": "arn:aws:iam::386104178260:role/eks-demo2-argocd-target"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRmFkeEJyNS9kMUl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFd01UVXhOREUyTWpSYUZ3MHpOVEV3TVRNeE5ESXhNalJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURtYk5lYWtXSGpyRVpBRFFNaGkvVFlaQUkycmU5QlpmdFk4MzJVenNIbGorUzlVOW5qTWQ2VTk1TDcKZVNUZTdaWXRKU0hZYWtDNjM2VWxoNUNqeXpqd1dyUlNsS2tLNlVGNDl1RkVSTW1ETmFqRllKdlcxd0NySzBxWApwc3ZUdjYwbXBlMWF2QzlyOUZkZEplTlIwUk8wMFJmSS9YRldKcGh6Q3ArTmpOcm94ekxYNXNHek5VRG00eGt4CnlUQkg0b0FON3pkS0pQS2JHTHZydUhsb3B5eXpTZEpaRVJWTUpCb3pRbWVzZkxpZ21MVCszWXZQWnZtRmpsZHIKN3NJbjd6cko2TlRVWVVOeHZxR1ZZWWd6NU1pWklpc2FScGkzSkJEQ0s1bkxSMjBTaExDU1JIRkV0bUNLRTBsYgoxazdNdk5DOEFySE51RThlZStTUjdFcmVFdXdYQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSSWdXS3RnbGUvTnNOandYY3YzSGlwZlBCd1hEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRRE1tWDVhMXgzTwp6OXo4TEJneGp4M1RQdVMycDlnRFlLNktzZUJHM0Y4cVVsbHJjVWQ1dlk1VGY5WVltSXBpNjRXT1VuSTk0L2puCjVEWjcvdkkxZDBIWXc1d0F5NFUyMjdXM2NRVlhHKzZ6dzRxWmFjUmVRaytyZzNZUnFMUlkveG82SHlobkFaZ1kKSVVxT3JzU2xqV2RJazVHYU90dTBXQk9melRhV2h0ZEhTWHpEU0c1M2FJKzMxeUF2Z0oyOW0ycnRTRE9kNm1aVgpzVTVINXlXMW14dE9WaklWUkJ0WFY3YUlCNUxudUNHek5LeVJsaThUZ3VjQ0M0UkRZTkpTcm1ZS1RXdGxzVzVvCjlRaldKSVdCVWdDQkFPZ2R2Z3FOa2hDbkR4b2RDOEl2Qm15aDV1dWd4YUJHaDNVZGJBb0tkUzdOaTdUOFc2MFcKbXNjU2JYSjN2dEMyCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      }
    }
