apiVersion: v1
kind: Secret
metadata:
  name: eks-integration
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: integration
type: Opaque
stringData:
  name: eks-integration
  server: https://E813554B1DC067E8A490361AE9A6DB62.gr7.us-east-1.eks.amazonaws.com
  config: |
    {
      "awsAuthConfig": {
        "clusterName": "eks-integration",
        "roleARN": "arn:aws:iam::022787320932:role/eks-integration-argocd-target"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRUNYb0V0YzdINWN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBNU1ETXlNREF5TWpCYUZ3MHpOVEE1TURFeU1EQTNNakJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMxWUd0T0I1ckl3VTNKeHNIcThXWFVhUktkbk9wUW9nTFpLRi9qMG0wTDVSc0w3QTRraEpZdnZFRDQKblcwdDJHWHdSUW9sTUtxcXQ3cDNQenM5dTBYcWFsMVQ1ZXZNNkFtTnlnWFBTSmVNUm9rUUZQa1Y1cnZaS1QvagpZMW1JcjE0T1NwSi96ZURpUStjenZtOGxvKzl6NlN3Q0t4SC9pRHdjSVUzWU5aUlB0SStObW9wNVY2VDdHdkpWClUvVU9WRDRaOE13MkpPbnAyZDVVVXMxKytDbHkvem9ra0EzVFc4NlEwRU1WZ0RGUVZrZEVNUVFTd25sbFdRN0QKN3RQWTUvcElWR0VmSzY0SHhQQ2dVQmVUMUdDWXhVUjVwd1k0MzhGU3VKMEVCSnJOV25YelpFZ0gwQ2hCeWhBdwpCVS83OGUzRjFrcENkY0pqdyttcnQ5ZGI0MU43QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRdHR4SzNJZ09KMHlXdzNLMlNNQllIS0JBZkFqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2toRk9yZSt4aQp0NkRqc1YrQzJvdEE2UEFwY0dpMmNsb0dxeSswK0FUUjBvV1FidEFaUjlJUVFUQWp4MVdrWUhSRXJaR21KSkd4Ck9HNTgrUnFKd0g1L3FoWUNEM3gyZldBa2grRlY3cXBNZFVqSFRkNHFTSXhEYlVOVnV4VkFSc0Rac01XSElyQ1QKa0dNN1JBelo2SGdOenZvQTR4UXBMM2pTVUdrTW5OcGNWZlFSQUNwRnZzV3lGOUxnZVNEWjhZWVhNSjVXTE1zTwpmdzA5am9YREd2U0VBSU5TQm4wamc4N2xvdU5XZXJvcE1jQ2c3azRLNWo5dmZoZjQzK3IreUNHYWRhd2ZSSVBRClpicWY1SkI2blVyaTM3RElKc2xYMU9rMkllcEdXdXFlZ0RxM3RjbnhBV0VUODFCVEdqL0RxSzFRVEo1N0JuWjkKVit0c1Ixb3N1WEJhCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      }
    }
