apiVersion: v1
kind: Secret
metadata:
  name: eks-uat
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: uat
type: Opaque
stringData:
  name: eks-uat
  server: https://E45C882B2DD0D374C63ED0C4C9DB2CFC.gr7.us-east-1.eks.amazonaws.com
  config: |
    {
      "awsAuthConfig": {
        "clusterName": "eks-uat",
        "roleARN": "arn:aws:iam::195355138577:role/eks-uat-argocd-target"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSnR1VVNEclczSzR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBNU1ETXhNakUzTURKYUZ3MHpOVEE1TURFeE1qSXlNREphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMvUWk2S3MzR0FYeWtOM1JOdDh5V0JIS0VwN084cmR0UUlyajZWYjcyMDh0UE40OUkyTTRvL09Yd1YKNmpCTmZxV2hSWlpQay95UkhTekhUdEFFMU85UzFyWTRhRitQeFRURVFqV3ZPUHhpMTNsRnNvKy9nYXIwRlJCTAp2a1Y3Q001Ym9jM3VIYkoxN3RjT0dNYjJhaWRMNFFzYUFUM1JUNmh6SzkxNGx1a05hVzFrai9LRkhBUElIZ0pRCmFlRk5sd1MyS0tHNi9IWi8yQXhxMFRsT1dveWJoQVlJMmFseTh1bUZFZmczRCsrTXAwTEVYVVV3anI2K1BxUnUKeGdCUTc0bERvQy8xV21Wa3lndTF0SE5uWTdsK05GRTYxaFdkYkE3c2crOFE5bGNGKzZuc3NSRExBK1FFb2FVdApaTzV5MGhFYmpEQmVpOFJyRWRJOTBnSHo5TmZ4QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTUDlkRDhDK0hQQUZGNzJsT3JJNFpkUWVQd1d6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkN4ZUdPa1V2QwpCUVpqdmlRbCtWL0JtSGM0ODVJK1pCRmZNb1BLM2VMNExoY3JlZmJoSDEvaFhvM3gwNldaclZRTmM1UGxLajkxCjZLMlFkZ3RaTWd6RGpvM2hBa1BPWXRpeFc5amRCRlRNclVpcHBsUzFVNDZ3NGhFRzd5TnVJWXVhOXhiR0w4ZFgKZlVDYmx0Y1pvSW9UYnpFOVRCZVN3cGl4VjJ4R2RtWTlEZ3FGTjQ2VFk1K1BuZS9kbXR2K3Z3cG9ScVRnakozbApzWEsxWHJzaXhRZ3EzZFlyVjBWMng1UnZhNlExQkg2bmZxak50cTZBODJtMzBDcFVxeGtISFZLVG84NE5mQkN5CjBvUnU5QUI2ZTVkSkVBTllISXpnbElVRTBHSXVNcmU3YnJIMEs1UFAxZ3hQc2MxY21xVmxOUDVyQUlSQjZxakEKTFliSW9uUDdvcmRuCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      }
    }
