configs:
  params:
    server.insecure: true

server:
  replicas: 1
  service:
    type: LoadBalancer
    loadBalancerClass: tailscale
    annotations:
      tailscale.com/expose: "true"
      tailscale.com/hostname: argocd

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

redis:
  enabled: true

dex:
  enabled: false

notifications:
  enabled: false
