global:
  domain: argocd.internal.nvisionx.ai

configs:
  params:
    server.insecure: true

server:
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: alb
    hostname: argocd.internal.nvisionx.ai
    path: /
    pathType: Prefix
    annotations:
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/inbound-cidrs: 10.4.0.0/16
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-3-2021-06
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-path: /healthz
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:787858641133:certificate/908c2ba5-41c3-4b61-ac92-e7dffbd4e087
      alb.ingress.kubernetes.io/group.name: argocd-internal

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

redis:
  enabled: true

dex:
  enabled: false

notifications:
  enabled: false
