# Control-plane overlay for our internal envs. Consumed by apps/control-plane.yaml.
project:
  name: nvisionx-development
  description: Workloads deployed to our internal EKS environments
  sourceRepos:
    - "https://github.com/Nvision-x/*"
    - "https://argoproj.github.io/argo-helm"
    - "ghcr.io/nvision-x"
    - "ghcr.io/nvision-x/*"
  destinations:
    - name: eks-development
      namespace: "*"
    - name: eks-integration
      namespace: "*"
    - name: eks-demo
      namespace: "*"
    - name: eks-demo2
      namespace: "*"
    - name: eks-uat
      namespace: "*"

environments:
  - name: development
    envRepo:
      url: https://github.com/Nvision-x/nxdeployment-development-env.git
      revision: main
  - name: integration
    envRepo:
      url: https://github.com/Nvision-x/nxdeployment-integration-env.git
      revision: main
  - name: demo
    envRepo:
      url: https://github.com/Nvision-x/nxdeployment-demo-env.git
      revision: main
  - name: demo2
    envRepo:
      url: https://github.com/Nvision-x/nxdeployment-demo2-env.git
      revision: main
  - name: uat
    envRepo:
      url: https://github.com/Nvision-x/nxdeployment-uat-env.git
      revision: main
